### ISSUE TITLE
Fix your CSRF and XSS vulnerabilities

### ISSUE THREAD

**Issue by StephanMeijer** [VanOns/laraberg-demo#30]
Don't Click :)

http://demo.laraberg.io/

<img width="451" alt="image" src="https://user-images.githubusercontent.com/3169264/164094177-6a76f2a1-55e6-40da-8634-a4b9177e6666.png">

**Comment by mauricewijnia** [comment]
Since the demo was using a pretty old version of laraberg, and we're looking to release v2 soon the demo site no longer serves a purpose. I will let the code live here, but I disabled to site to prevent any issues in the future.
